### ISSUE TITLE
Setup Travis CI for project

### ISSUE THREAD

**Issue by xSavitar** [ch3nkula/url-shortener#10]
Travis CI should be setup for the repo / project for automated testing to be done before review is carried out on PR and/or the project. Consider a minimum PHP version of 5.6 for the project.

**Comment by netcode** [comment]
I don't see any tests on the project , I can setup a Travis CI configuration file , but it will be useless without any unit test included.

**Comment by xSavitar** [comment]
You could help write up some unit tests for the app :)
