### ISSUE TITLE
Short URL is based on localhost host.

### ISSUE THREAD

**Issue by GSokol** [ch3nkula/url-shortener#26]
On production it returns something like `localhost:3000/shortener.php/zdjmmwiy` and writes it to DB so it's impossible to get the right redirect.

**Comment by xSavitar** [comment]
Thanks for this issue @GSokol. Will be waiting your patch. Thanks :)

**Comment by xSavitar** [comment]
As a heads up, I think the issue is here: https://github.com/ch3nkula/url-shortener/blob/master/php/shorten.php#L8. By removing `dev` as default argument to constructor (and leaving just `""`), this should do the job. :)

**Comment by GSokol** [comment]
https://github.com/ch3nkula/url-shortener/pull/27 FIX it
